# Generated by Django 5.1.3 on 2026-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('vendor_type', models.CharField(max_length=50)),
                ('pan_available', models.CharField(max_length=10)),
                ('tds_rate', models.FloatField()),
                ('tds_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
